<h1 class="mt-2">Task editor</h1>
<form action="<?php echo $view->getPath('/tasks/submit') ?>">
    <input type="hidden" name="id" value="<?php echo $view->get('task')->id; ?>">
    <input type="hidden" name="page" value="<?php echo $view->get('page'); ?>">
    <input type="hidden" name="order" value="<?php echo $view->get('order'); ?>">
    <input type="hidden" name="direction" value="<?php echo $view->get('direction'); ?>">
    <div class="form-group">
        <label for="inputName">Name</label>
        <input type="text" name="name" value="<?php echo $view->get('task')->name; ?>" class="form-control" required id="inputName">
    </div>
    <div class="form-group">
        <label for="inputEmail">Email address</label>
        <input type="email" name="email" value="<?php echo $view->get('task')->email; ?>" class="form-control" required id="inputEmail" aria-describedby="emailHelp">
    </div>
    <div class="form-group">
        <label for="inputText">Text</label>
        <textarea class="form-control" required name="text" id="inputText" rows="3"><?php echo $view->get('task')->text; ?></textarea>
    </div>
    <div class="form-group form-check">
        <input type="checkbox" name="completed" <?php echo $view->get('task')->completed ? 'checked="checked"' : ''; ?> class="form-check-input" id="inputCompleted">
        <label class="form-check-label" for="inputCompleted">Task completed</label>
    </div>
    <button type="submit" class="btn btn-primary">Save</button>
</form>
